### ISSUE TITLE
Explaining why ex_09_04.py commented out code has more values

### ISSUE THREAD

**Issue by nt591** [kylejb/py4e-student-repo#1]
https://github.com/kylejb/py4e-student-repo/blob/master/2_Python-Data-Structures/ch_09/ex_09_04.py _[updated url -kylejb]_

Think  about what you wrote and lets walk through it

`words = line.split()`

First off, what is line? It's undefined at this block, but let's write the code I think you had that's breaking.

```python
for line in handle:
  words = line.split()
  for word in words:
# Parameter to focus only on lines starting with "From "
    if line.startswith("From "):
      email = words[1]
      print(email)
    counts[email] = counts.get(email, 0) + 1
```

Ok, let's stub some data

`line = "From nikhil@example.com on Dec 13 2019"`
`words = ["From", "nikhil@example.com", "on", "Dec", "13", "2019"]`
Now you run `for word in words`, which is 6 iterations of your loop. That means 6 times you run this code

```python
    if line.startswith("From "):
      email = words[1]
      print(email)
    counts[email] = counts.get(email, 0) + 1
 ```

For the exact same line. Before you even get to line 2 in the file, you've added my email 6 times because you're checking for every word. You just want to check each line in the file.

**Comment by kylejb** [comment]
Thanks Nikhil!

> `words = line.split()`
> 
> First off, what is line? It's undefined at this block... 

Good catch. I was trying to globally define **words** within the main loop, but the problem with the logic here is that **line** has yet to be defined since it's outside the subsequent loop that calls **line** as an iterative variable, right? 

Proposed Solutions:

**Delete** : it doesn't seem to have an effect on output surprisingly
_I thought I needed to split the data once more for the second loop since it wasn't nested_

QUESTIONS

1. Why isn't it necessary to call split() method in this as originally written? Is it because I stored the split data in dict? If so, then can the loop be improved by having the iterative variable read through the dict rather than the file?

1. Would it be best if the code in question was a nested - indenting four spaces from `for lines in handle` - loop rather than a separate one?

 

> Ok, let's stub some data
> 
> `line = "From nikhil@example.com on Dec 13 2019"`
> `words = ["From", "nikhil@example.com", "on", "Dec", "13", "2019"]`
> Now you run `for word in words`, which is 6 iterations of your loop. That means 6 times you run this code
> 
> ```python
>     if line.startswith("From "):
>       email = words[1]
>       print(email)
>     counts[email] = counts.get(email, 0) + 1
> ```
> 
> For the exact same line. Before you even get to line 2 in the file, you've added my email 6 times because you're checking for every word. You just want to check each line in the file.

It makes sense because I trust you, but I don't fully see the issue.  When you have a minute, would you mind walking me through this once more?

I thought I needed to read through each word in the line in order to identify and store the targeted email address. Isn't the only alternative simply calling the location within the line, if it is known? In this case it is, but I wonder how one would do so without this knowledge if not reading through each word in a line.

Thanks again for the insight.  It's tough - and feels nearly impossible - to go at this alone.
